// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIF_3CP_5lqIFhPISnf_cqKwCLXfwMQk',
    appId: '1:226195233828:web:70bc948d18504ba86b8cb1',
    messagingSenderId: '226195233828',
    projectId: 'smell-of-spokes',
    authDomain: 'smell-of-spokes.firebaseapp.com',
    storageBucket: 'smell-of-spokes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQJoQk6Hx4hWyObbxLl_fEeqcSUg3GwM',
    appId: '1:226195233828:android:1250d327518c962a6b8cb1',
    messagingSenderId: '226195233828',
    projectId: 'smell-of-spokes',
    storageBucket: 'smell-of-spokes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhl1QtTyIo258IzGeNNHlvz-xl3Nkv7NM',
    appId: '1:226195233828:ios:d6d7a0dc3db46bd86b8cb1',
    messagingSenderId: '226195233828',
    projectId: 'smell-of-spokes',
    storageBucket: 'smell-of-spokes.appspot.com',
    iosBundleId: 'com.example.smellOfSpokes',
  );
}
